### ISSUE TITLE
SPARQL queries fail through powergridmodels api.

### ISSUE THREAD

**Issue by afisher1** [PNNL-CIM-Tools/CIM-Graph#30]
**Describe the bug**
calling get_all_attributes(cim.PowerTransformer) results in the following error in the gridappsd platform.

2023-07-18 17:38:35,274 Thread-39 **ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1689701915229|gov.pnnl.goss.gridappsd.process.ProcessEvent|553773426|ERROR|system|ERROR
org.apache.jena.query.QueryParseException: Variable used when already in-scope: ?PowerTransformerEnd in ((AGG ?.0 GROUP_CONCAT(DISTINCT ?PowerTransformerEnd ; separator=';')) AS ?PowerTransformerEnd)**
        at org.apache.jena.sparql.lang.SyntaxVarScope.checkAssignment(SyntaxVarScope.java:194)
        at org.apache.jena.sparql.lang.SyntaxVarScope.lambda$checkExprListAssignment$0(SyntaxVarScope.java:142)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.apache.jena.sparql.core.VarExprList.forEachExpr(VarExprList.java:70)
        at org.apache.jena.sparql.lang.SyntaxVarScope.checkExprListAssignment(SyntaxVarScope.java:137)
        at org.apache.jena.sparql.lang.SyntaxVarScope.checkQueryScope(SyntaxVarScope.java:94)
        at org.apache.jena.sparql.lang.SyntaxVarScope.check(SyntaxVarScope.java:64)
        at org.apache.jena.sparql.lang.SPARQLParser.validateParsedQuery(SPARQLParser.java:55)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:35)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:40)
        at gov.pnnl.goss.gridappsd.data.handlers.BlazegraphQueryHandler.query(BlazegraphQueryHandler.java:96)
        at gov.pnnl.goss.gridappsd.data.BGPowergridModelDataManagerImpl.queryResultSet(BGPowergridModelDataManagerImpl.java:226)
        at gov.pnnl.goss.gridappsd.data.BGPowergridModelDataManagerImpl.query(BGPowergridModelDataManagerImpl.java:201)
        at gov.pnnl.goss.gridappsd.data.BGPowergridModelDataManagerHandlerImpl.handle(BGPowergridModelDataManagerHandlerImpl.java:32)
        at gov.pnnl.goss.gridappsd.data.DataManagerImpl.processDataRequest(DataManagerImpl.java:149)
        at gov.pnnl.goss.gridappsd.process.ProcessEvent.onMessage(ProcessEvent.java:264)
        at pnnl.goss.core.client.GossClient$1.run(GossClient.java:398)
        at java.lang.Thread.run(Thread.java:750)

The actual call that fails is in cimgraph/loaders/gridappsd/__init__.py GridappsdConnection.query_data()
it calls GridAPPSD.query_data() method with the following python string:

'\n        PREFIX r:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n        PREFIX cim:  <http://iec.ch/TC57/CIM100#>\n        SELECT ?mRID ?name ?Location ?vectorGroup ?aggregate ?inService\n        (group_concat(distinct ?PowerTransformerEnd; separator=";") as ?PowerTransformerEnd) \n        (group_concat(distinct ?TransformerTank; separator=\';\') as ?TransformerTanks)\n        (group_concat(distinct ?Terminal; separator=\';\') as ?Terminals)\n        (group_concat(distinct ?Measurement; separator=";") as ?Measurements) \n        (group_concat(distinct ?Asset; separator=";") as ?Assets) \n        \n        WHERE {          \n          ?eq r:type cim:PowerTransformer.\n          VALUES ?fdrid {"_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62"}\n          VALUES ?mRID { "_1E6B5C97-C4E8-4CED-B9A5-6E69F389DA93" \n "_259E820F-B4AF-4E1A-8271-687534EDAECC" \n "_67B57539-590B-4158-9CBB-9DBA2FE6C1F0" \n "_7FF12CEF-1C4D-4CD2-8FCC-662530A7BA33" \n               } \n         ?eq cim:Equipment.EquipmentContainer ?fdr.\n        ?fdr cim:IdentifiedObject.mRID ?fdrid.\n\n        ?eq cim:IdentifiedObject.mRID ?mRID.\n        ?eq cim:IdentifiedObject.name ?name.\n\n        OPTIONAL {?eq cim:PowerSystemResource.Location ?loc.\n        ?loc cim:IdentifiedObject.mRID ?Location.}\n\n        OPTIONAL {?eq cim:PowerTransformer.vectorGroup ?vectorGroup.}\n        OPTIONAL {?eq cim:Equipment.aggregate ?aggregate.}\n        OPTIONAL {?eq cim:Equipment.inService ?inService.}\n        #OPTIONAL {?eq cim:Equipment.networkAnalysisEnable ?networkAnalysisEnabled.}\n        #OPTIONAL {?eq cim:Equipment.normallyInService ?normallyInService.}\n        \n        OPTIONAL {?asset cim:Asset.PowerSystemResources ?eq.\n                  ?asset cim:IdentifiedObject.mRID ?Asset.}\n\n        OPTIONAL {?tank cim:TransformerTank.PowerTransformer ?eq.\n                  ?tank cim:IdentifiedObject.mRID ?TransformerTank.}\n\n        OPTIONAL {?end cim:PowerTransformerEnd.PowerTransformer ?eq.\n                  ?end cim:IdentifiedObject.mRID ?PowerTransformerEnd.}\n                  \n        OPTIONAL {?t cim:Terminal.ConductingEquipment ?eq.\n                  ?t cim:IdentifiedObject.mRID ?Terminal.}\n        OPTIONAL {?meas cim:Measurement.PowerSystemResource ?eq.\n            ?meas cim:IdentifiedObject.mRID ?meas_id.\n            ?meas a ?meas_cls.\n            bind(concat(str(?meas_id),",",strafter(str(?meas_cls),"CIM100#")) as ?Measurement).}\n                  \n        }\n        GROUP by ?mRID ?name ?Location ?vectorGroup ?aggregate ?inService\n        ORDER by ?name\n        '

it chokes on the first line with double quotes. I've attempted to supply a backslash to this string which results in  a different parsing error.

2023-07-18 18:27:05,471 Thread-39 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1689704825430|gov.pnnl.goss.gridappsd.process.ProcessEvent|1088478367|ERROR|system|ERROR
org.apache.jena.query.QueryParseException: Encountered " <ECHAR> "\\\' "" at line 5, column 64.
Was expecting one of:
    <STRING_LITERAL1> ...
    <STRING_LITERAL2> ...
    <STRING_LITERAL_LONG1> ...
    <STRING_LITERAL_LONG2> ...

        at org.apache.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:100)
        at org.apache.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:40)
        at gov.pnnl.goss.gridappsd.data.handlers.BlazegraphQueryHandler.query(BlazegraphQueryHandler.java:96)
        at gov.pnnl.goss.gridappsd.data.BGPowergridModelDataManagerImpl.queryResultSet(BGPowergridModelDataManagerImpl.java:226)
        at gov.pnnl.goss.gridappsd.data.BGPowergridModelDataManagerImpl.query(BGPowergridModelDataManagerImpl.java:201)
        at gov.pnnl.goss.gridappsd.data.BGPowergridModelDataManagerHandlerImpl.handle(BGPowergridModelDataManagerHandlerImpl.java:32)
        at gov.pnnl.goss.gridappsd.data.DataManagerImpl.processDataRequest(DataManagerImpl.java:149)
        at gov.pnnl.goss.gridappsd.process.ProcessEvent.onMessage(ProcessEvent.java:264)
        at pnnl.goss.core.client.GossClient$1.run(GossClient.java:398)
        at java.lang.Thread.run(Thread.java:750)

I'm not sure what the proper fix is for this.

**Comment by afisher1** [comment]
The issue was bad syntax in the sparql queries that were ignored when sent to blazegraph directly. Fixed and closing.

**Comment by AAndersn** [comment]
Similar problem for https://github.com/PNNL-CIM-Tools/CIM-Graph/blob/develop/cimgraph/loaders/sparql/rc4_2021/energy_consumer.py#L27
